viamclassifier:
  enabled: false
  path: 'modules.viam.viamclassifier.ViamClassifier'
  config:
    classifier_name: 'my-classifier'
    camera_name: 'camera'
  dependencies:
    python:
      - viam-sdk
viamobjectdetection:
  enabled: false
  path: 'modules.viam.viamobjects.ViamObjects'
  config:
    vision_client: 'objectDetector'
    camera_name: 'camera'
    timelapse_location: '/home/archie/modular-biped/data/viamobjects'
  dependencies:
    python:
      - viam-sdk
    additional:
      - https://docs.viam.com/installation/viam-server-setup/