vision:
  enabled: true
  path: 'modules.vision.imx500.vision.Vision'
  config:
    preview: False
  dependencies:
    unix:
      - imx500-all
    python:
      - python3-opencv
      - python3-munkres
